
export enum ScreenName {
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  HOME = 'HOME',
  SUBJECTS = 'SUBJECTS',
  SUBJECT_DETAILS = 'SUBJECT_DETAILS',
  LESSONS = 'LESSONS',
  LEARN = 'LEARN',
  REVISION = 'REVISION',
  REVISION_DETAILS = 'REVISION_DETAILS',
  MOCK_TEST = 'MOCK_TEST',
  PROFILE = 'PROFILE',
  SETTINGS = 'SETTINGS',
  GOALS = 'GOALS',
  ANALYTICS = 'ANALYTICS',
  CALENDAR = 'CALENDAR',
  LEADERBOARD = 'LEADERBOARD',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  ADMIN_PORTAL = 'ADMIN_PORTAL',
  AI_USAGE='AI-USAGE'
}
